/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface AccessoriesTbEntity {
  'id'?: number;
  'image': string;
  'market_id': number;
  'name': string;
  'price': number;
}


export const AccessoriesTbAttributes = [
    "id",
    "image",
    "market_id",
    "name",
    "price"
];