/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface CategoriesTbEntity {
  'id'?: number;
  'id_market': number;
  'name': string;
}


export const CategoriesTbAttributes = [
    "id",
    "id_market",
    "name"
];