/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface CategoriesTbEntity {
  'id'?: number;
  'market_id': number;
  'name': string;
}


export const CategoriesTbAttributes = [
    "id",
    "market_id",
    "name"
];