/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface GalleriesTbEntity {
  'id'?: number;
  'image': string;
  'market_id': number;
}


export const GalleriesTbAttributes = [
    "id",
    "image",
    "market_id"
];