/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface GalleriesTbEntity {
  'id'?: number;
  'id_market': number;
  'image': string;
}


export const GalleriesTbAttributes = [
    "id",
    "id_market",
    "image"
];