/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface MarketDaysTbEntity {
  'dayname': string;
  'id'?: number;
  'market_id': number;
}


export const MarketDaysTbAttributes = [
    "dayname",
    "id",
    "market_id"
];