/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface MarketTbEntity {
  'admin_id'?: number | null;
  'created_at'?: string | null;
  'detail': string;
  'id'?: number;
  'id_card_number'?: string | null;
  'image': string;
  'image_plan': string;
  'key': string;
  'lat': string;
  'lon': string;
  'mobile_number'?: string | null;
  'name': string;
  'service_price': number;
  'time_close': string;
  'time_open': string;
  'updated_at'?: string | null;
}


export const MarketTbAttributes = [
    "admin_id",
    "created_at",
    "detail",
    "id",
    "id_card_number",
    "image",
    "image_plan",
    "key",
    "lat",
    "lon",
    "mobile_number",
    "name",
    "service_price",
    "time_close",
    "time_open",
    "updated_at"
];