/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface MarketOpenReserveDaysTbEntity {
  'dayname': string;
  'id'?: number;
  'id_market': number;
}


export const MarketOpenReserveDaysTbAttributes = [
    "dayname",
    "id",
    "id_market"
];