/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface NotificationEntity {
  'date': string;
  'id'?: number;
  'line_id': string;
  'order_id': number;
  'section_zone_id': number;
  'status': number;
}


export const NotificationAttributes = [
    "date",
    "id",
    "line_id",
    "order_id",
    "section_zone_id",
    "status"
];