/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface OrderAccessoryTbEntity {
  'assessory_id': number;
  'id'?: number;
  'order_id': number;
  'price': number;
  'quantity': number;
}


export const OrderAccessoryTbAttributes = [
    "assessory_id",
    "id",
    "order_id",
    "price",
    "quantity"
];