/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface OrderSectionZoneTbEntity {
  'id'?: number;
  'order_id': number;
  'price': number;
  'section_zone_id': number;
  'section_zone_name': string;
}


export const OrderSectionZoneTbAttributes = [
    "id",
    "order_id",
    "price",
    "section_zone_id",
    "section_zone_name"
];