/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface OrderSectionZoneDayTbEntity {
  'date': string;
  'day': string;
  'id'?: number;
  'order_section_zone_id': number;
}


export const OrderSectionZoneDayTbAttributes = [
    "date",
    "day",
    "id",
    "order_section_zone_id"
];