/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface OwnersTbEntity {
  'fname': string;
  'created_at': string;
  'email': string;
  'id'?: number;
  'lname': string;
  'password': string;
  'updated_at': string;
}


export const OwnersTbAttributes = [
    " fname",
    "created_at",
    "email",
    "id",
    "lname",
    "password",
    "updated_at"
];