/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface PointTbEntity {
  'area_id': number;
  'axis_x': number;
  'axis_y': number;
  'id'?: number;
  'type_area': string;
}


export const PointTbAttributes = [
    "area_id",
    "axis_x",
    "axis_y",
    "id",
    "type_area"
];