/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface SectionZoneTbEntity {
  'id'?: number;
  'image'?: string | null;
  'name': string;
  'price': number;
  'shape': string;
  'status': string;
  'zone_id': number;
}


export const SectionZoneTbAttributes = [
    "id",
    "image",
    "name",
    "price",
    "shape",
    "status",
    "zone_id"
];