/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface UserTbEntity {
  'created_at'?: string | null;
  'email'?: string | null;
  'id'?: number;
  'image': string;
  'line_id': string;
  'line_username': string;
  'market_id'?: number | null;
  'phone'?: string | null;
  'type_user': string;
  'updated_at'?: string | null;
}


export const UserTbAttributes = [
    "created_at",
    "email",
    "id",
    "image",
    "line_id",
    "line_username",
    "market_id",
    "phone",
    "type_user",
    "updated_at"
];