/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface ZoneTbEntity {
  'color': string;
  'id'?: number;
  'image_plan': string;
  'market_id': number;
  'name': string;
  'shape': string;
}


export const ZoneTbAttributes = [
    "color",
    "id",
    "image_plan",
    "market_id",
    "name",
    "shape"
];