/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface ZoneCategoriesTbEntity {
  'category_id': number;
  'id'?: number;
  'zone_id': number;
}


export const ZoneCategoriesTbAttributes = [
    "category_id",
    "id",
    "zone_id"
];