/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface ZoneTbEntity {
  'color': string;
  'height': number;
  'id'?: number;
  'image_plan': string;
  'market_id': number;
  'name': string;
  'pos_left': number;
  'pos_top': number;
  'quantity_section'?: number | null;
  'width': number;
}


export const ZoneTbAttributes = [
    "color",
    "height",
    "id",
    "image_plan",
    "market_id",
    "name",
    "pos_left",
    "pos_top",
    "quantity_section",
    "width"
];